package com.heavybox.jtix.widgets_2;

public enum Anchor {

    PARENT_TOP_LEFT,    PARENT_TOP_CENTER,    PARENT_TOP_RIGHT,
    PARENT_CENTER_LEFT, PARENT_CENTER_CENTER, PARENT_CENTER_RIGHT,
    PARENT_BOTTOM_LEFT, PARENT_BOTTOM_CENTER, PARENT_BOTTOM_RIGHT,

    CURSOR_TOP_LEFT,    CURSOR_TOP_CENTER,    CURSOR_TOP_RIGHT,
    CURSOR_CENTER_LEFT, CURSOR_CENTER_CENTER, CURSOR_CENTER_RIGHT,
    CURSOR_BOTTOM_LEFT, CURSOR_BOTTOM_CENTER, CURSOR_BOTTOM_RIGHT,
    ;

}
