package com.heavybox.jtix.userinterface;

public enum Anchor {

    PARENT_TOP_LEFT,    PARENT_TOP_CENTER,    PARENT_TOP_RIGHT,
    PARENT_CENTER_LEFT, PARENT_CENTER_CENTER, PARENT_CENTER_RIGHT,
    PARENT_BOTTOM_LEFT, PARENT_BOTTOM_CENTER, PARENT_BOTTOM_RIGHT,
    ;

}
